#ifndef __WEB_H
#define __WEB_H
const uint8_t username[]={"a"};
const uint8_t web[]={
"<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">"
"<html xmlns=\"http://www.w3.org/1999/xhtml\">"
"<head>"
"<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />"
"<title>LED Control</title>"
"</head>"
"<body bgcolor=\"gray\">"
"<center>"
"<font size=\"+6\">LED CONTROL</font><br /><br />"
"<font size=\"+4\">Ethernet Project</font><br /><br />"
"<img src=\"http://4.bp.blogspot.com/-l6h4jURg0vw/ThfDD39lsKI/AAAAAAAAAeI/I4YNdqPAk8k/s1600/boss.png\" /><br /><br>"
"<form method=\"post\" action=\"\">"
"<table border=\"1\">"
"<tr>"
"<td>LED LAM: <br />"
"<input type=\"radio\" name=\"LED1\" value=\"1\" />ON<br>"
"<input type=\"radio\" name=\"LED1\" value=\"0\" />OFF<br />"
"</td>"
"<td>LED CAM: <br />"
"<input type=\"radio\" name=\"LED2\" value=\"1\" />ON<br>"
"<input type=\"radio\" name=\"LED2\" value=\"0\" />OFF<br />"
"</td>"
"<td>LED LUC: <br />"
"<input type=\"radio\" name=\"LED3\" value=\"1\" />ON<br>"
"<input type=\"radio\" name=\"LED3\" value=\"0\" />OFF<br />"
"</td>"
"</tr>"
"</table><br>"
"<input type=\"submit\" name=\"SUBMIT\"value=\"SEND\" />"
"</form>"
"B K U<br />"
"VMLAB<br />"
"</center>"
"</body>"
"</html>"
};

const uint8_t formlogin[]={
"<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\"\"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">"
"<html xmlns=\"http://www.w3.org/1999/xhtml\">"
"<head>"
"<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />"
"<title>Form Dang Nhap</title>"
"</head>"
"<body>"
"<form action=\"\"method =\"post\">"
"<table witdh =\"4000\" height=\"200\" border=\"2\" align=\"center\">"
"<tr>"
"<th colspan=\"2\" align=\"center\"> DANG NHAP</th>"
"</tr>"
"<td>Ten dang nhap</td>"
"<td><input type =\"text\" placeholder =\"nhap ten dang nhap\" size =\"40\" name =\"txtname\" /></td>"
"<tr>"
"<td>Mat khau</td>"
"<td><input type =\"password\" placeholder =\"nhap mat khau\" size=\"40\" name =\"txtpass\" /></td>"   
"</tr>"
"<tr>"
"<td colspan=\"2\" align=\"center\">"
"<input type =\"reset\" name=\"btreset\" value =\"Reset\" />"
"<input type =\"submit\" name =\"btok\" value =\"OK\" />"
"</td>"
"</tr>"
"</table>"
"</form>"
"</body>"
"</html>"
};

#endif
